version: "3.9" # optional since v1.27.0

services:
  fhir-server:
    image: ghcr.io/chgl/hapi-fhir-jpaserver-starter:1.0.0-hapi5.3.0-distroless
    restart: unless-stopped
    ports:
      - ${PORT_HAPI_FHIR:-127.0.0.1:8081}:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://fhir-server-db:5432/fhir?currentSchema=public"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQL10Dialect
      VALIDATION_REQUESTS_ENABLED: "false"
      HAPI_FHIR_USE_APACHE_ADDRESS_STRATEGY: "true"
      HAPI_FHIR_ENFORCE_REFERENTIAL_INTEGRITY_ON_DELETE: ${HAPI_FHIR_ENFORCE_REFERENTIAL_INTEGRITY_ON_DELETE:-TRUE}
      HAPI_FHIR_ENFORCE_REFERENTIAL_INTEGRITY_ON_WRITE: ${HAPI_FHIR_ENFORCE_REFERENTIAL_INTEGRITY_ON_WRITE:-TRUE}
    depends_on:
      - fhir-server-db

  fhir-server-db:
    image: postgres:12.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir
